### ISSUE TITLE
Getting an error when installing WeaverCore

### ISSUE THREAD

**Issue by Tulip-0333** [nickc01/WeaverCore#2]
Unable to resolve reference 'Assembly-CSharp' is in the console instead of what it should be. Could someone help?

**Comment by nickc01** [comment]
Do you know what platform you are on (Windows, Mac, Linux)?

Is there anything else being shown in the console? Are you able to show a screenshot of it? You are able to click on the error message in the console to display more info, like in this example screenshot:

![Example Error Message](https://user-images.githubusercontent.com/12601671/149607691-7adf304a-568e-46fb-9409-55c558f630d5.PNG)

Do you know where your Hollow Knight installation is located?

These questions will help me narrow down the root cause of the issue

**Comment by Tulip-0333** [comment]
I am on Windows, and my HK installation is in D:\SteamLibrary\steamapps\common\Hollow Knight
Sorry for responding so late, I forgot I made this issue.
